### ISSUE TITLE
BlueZ

### ISSUE THREAD

**Issue by bararchy** [oprypin/crystal-dbus#1]
Hi @oprypin 
I want to use your project to interface against BlueZ via dbus.
Could you add shard example? also, the example code will live better in the spec part ? 

Thanks :)

**Comment by oprypin** [comment]
I think the project works and the example is there. Feel free to send a pull request that rearranges files and adds shard.yml. I do not intend to get back into dbus stuff after 2 years  :|

**Comment by bararchy** [comment]
@oprypin I see, it seems example and code are working, I'll send a PR for the README file, I'll try to followup with anything else I might add\change and you can see if you like it.

**Comment by bararchy** [comment]
@oprypin maybe you nudge me in the right direction, how can I get the value in the picture from the code

![pic](https://sc-cdn.scaleengine.net/i/63fb41d6d4f20f136ecc38a305c22cba1.png)

code
```crystal
require "dbus"

bus = DBus::Bus.new

dest = bus.destination("org.bluez.hci1")
puts "Dest: #{dest}"
obj = dest.object("/org/bluez/hci1")
puts "Obj: #{obj}"
int = obj.interface("org.bluez.Adapter1")
puts "Interface: #{int}"
int.call("StartDiscovery")
int.call("GetDiscoveryFilters").reply
sleep 2
int.call("StopDiscovery")
```

**Comment by oprypin** [comment]
Discussed this in chat.
Getting a property is exactly the same as calling a method.
